"""Generate sample report for screenshot."""
from aifme_scout.engine.summary import summarize
from aifme_scout.extractors.models import (
    EvidenceItem,
    EvidenceProvenance,
    ScoutMeta,
    ScoutSchema,
    ScoutSite,
)

schema = ScoutSchema(
    meta=ScoutMeta(
        schema_version="1.0.0",
        engine_version="1.0.0-rc3",
        timestamp="2024-01-01T00:00:00+00:00",
    ),
    site=ScoutSite(url="https://python.org", target_url="https://python.org"),
    seo=[
        EvidenceItem(
            evidence_id="ev-001",
            evidence_type="SEO_TITLE",
            extractor_source="seo",
            value="Welcome to Python.org",
            provenance=EvidenceProvenance(page_url="https://python.org"),
            confidence="high",
            page_url="https://python.org",
            timestamp="2024-01-01T00:00:00+00:00",
        ),
        EvidenceItem(
            evidence_id="ev-002",
            evidence_type="META_DESCRIPTION",
            extractor_source="seo",
            value="The official home of the Python Programming Language",
            provenance=EvidenceProvenance(page_url="https://python.org"),
            confidence="high",
            page_url="https://python.org",
            timestamp="2024-01-01T00:00:00+00:00",
        ),
        EvidenceItem(
            evidence_id="ev-003",
            evidence_type="CANONICAL",
            extractor_source="seo",
            value="https://python.org",
            provenance=EvidenceProvenance(page_url="https://python.org"),
            confidence="high",
            page_url="https://python.org",
            timestamp="2024-01-01T00:00:00+00:00",
        ),
        EvidenceItem(
            evidence_id="ev-004",
            evidence_type="LANGUAGE",
            extractor_source="seo",
            value={"value": "en"},
            provenance=EvidenceProvenance(page_url="https://python.org"),
            confidence="high",
            page_url="https://python.org",
            timestamp="2024-01-01T00:00:00+00:00",
        ),
        EvidenceItem(
            evidence_id="ev-005",
            evidence_type="CHARSET",
            extractor_source="seo",
            value="UTF-8",
            provenance=EvidenceProvenance(page_url="https://python.org"),
            confidence="high",
            page_url="https://python.org",
            timestamp="2024-01-01T00:00:00+00:00",
        ),
        EvidenceItem(
            evidence_id="ev-006",
            evidence_type="VIEWPORT",
            extractor_source="seo",
            value="width=device-width, initial-scale=1",
            provenance=EvidenceProvenance(page_url="https://python.org"),
            confidence="high",
            page_url="https://python.org",
            timestamp="2024-01-01T00:00:00+00:00",
        ),
        EvidenceItem(
            evidence_id="ev-007",
            evidence_type="STRUCTURED_DATA",
            extractor_source="seo",
            value={"has_json_ld": True, "has_microdata": False, "has_rdfa": False},
            provenance=EvidenceProvenance(page_url="https://python.org"),
            confidence="high",
            page_url="https://python.org",
            timestamp="2024-01-01T00:00:00+00:00",
        ),
    ],
    metadata=[
        EvidenceItem(
            evidence_id="ev-008",
            evidence_type="SITE_NAME",
            extractor_source="metadata",
            value="Python.org",
            provenance=EvidenceProvenance(page_url="https://python.org"),
            confidence="high",
            page_url="https://python.org",
            timestamp="2024-01-01T00:00:00+00:00",
        ),
        EvidenceItem(
            evidence_id="ev-009",
            evidence_type="FAVICON",
            extractor_source="metadata",
            value="https://python.org/static/favicon.ico",
            provenance=EvidenceProvenance(page_url="https://python.org"),
            confidence="high",
            page_url="https://python.org",
            timestamp="2024-01-01T00:00:00+00:00",
        ),
        EvidenceItem(
            evidence_id="ev-010",
            evidence_type="RSS_FEED",
            extractor_source="metadata",
            value="https://python.org/feeds/news.xml",
            provenance=EvidenceProvenance(page_url="https://python.org"),
            confidence="high",
            page_url="https://python.org",
            timestamp="2024-01-01T00:00:00+00:00",
        ),
    ],
    technology=[
        EvidenceItem(
            evidence_id="ev-011",
            evidence_type="TECHNOLOGY",
            extractor_source="technology",
            value={
                "name": "Python",
                "category": "language",
                "confidence": "high",
                "detection_method": "fingerprint",
            },
            provenance=EvidenceProvenance(page_url="https://python.org"),
            confidence="high",
            page_url="https://python.org",
            timestamp="2024-01-01T00:00:00+00:00",
        ),
        EvidenceItem(
            evidence_id="ev-012",
            evidence_type="TECHNOLOGY",
            extractor_source="technology",
            value={
                "name": "Nginx",
                "category": "web-server",
                "confidence": "high",
                "detection_method": "fingerprint",
            },
            provenance=EvidenceProvenance(page_url="https://python.org"),
            confidence="high",
            page_url="https://python.org",
            timestamp="2024-01-01T00:00:00+00:00",
        ),
    ],
    content=[
        EvidenceItem(
            evidence_id="ev-013",
            evidence_type="CONTENT_HEADING",
            extractor_source="content",
            value={"level": 1, "text": "Welcome to Python.org"},
            provenance=EvidenceProvenance(page_url="https://python.org"),
            confidence="high",
            page_url="https://python.org",
            timestamp="2024-01-01T00:00:00+00:00",
        ),
        EvidenceItem(
            evidence_id="ev-014",
            evidence_type="CONTENT_HEADING",
            extractor_source="content",
            value={"level": 2, "text": "Downloads"},
            provenance=EvidenceProvenance(page_url="https://python.org"),
            confidence="high",
            page_url="https://python.org",
            timestamp="2024-01-01T00:00:00+00:00",
        ),
        EvidenceItem(
            evidence_id="ev-015",
            evidence_type="CONTENT_HEADING",
            extractor_source="content",
            value={"level": 2, "text": "Documentation"},
            provenance=EvidenceProvenance(page_url="https://python.org"),
            confidence="high",
            page_url="https://python.org",
            timestamp="2024-01-01T00:00:00+00:00",
        ),
        EvidenceItem(
            evidence_id="ev-016",
            evidence_type="CONTENT_HEADING",
            extractor_source="content",
            value={"level": 2, "text": "Community"},
            provenance=EvidenceProvenance(page_url="https://python.org"),
            confidence="high",
            page_url="https://python.org",
            timestamp="2024-01-01T00:00:00+00:00",
        ),
    ],
    social=[
        EvidenceItem(
            evidence_id="ev-017",
            evidence_type="SOCIAL_PROFILE",
            extractor_source="social",
            value={
                "platform": "GitHub",
                "url": "https://github.com/python",
                "username": "python",
            },
            provenance=EvidenceProvenance(page_url="https://python.org"),
            confidence="high",
            page_url="https://python.org",
            timestamp="2024-01-01T00:00:00+00:00",
        ),
    ],
    competitors=[
        EvidenceItem(
            evidence_id="ev-018",
            evidence_type="COMPETITOR",
            extractor_source="competitors",
            value={"name": "Ruby", "url": "https://ruby-lang.org"},
            provenance=EvidenceProvenance(page_url="https://python.org"),
            confidence="medium",
            page_url="https://python.org",
            timestamp="2024-01-01T00:00:00+00:00",
        ),
    ],
    evidence=[
        EvidenceItem(
            evidence_id="ev-001",
            evidence_type="SEO_TITLE",
            extractor_source="seo",
            value="Welcome to Python.org",
            provenance=EvidenceProvenance(page_url="https://python.org"),
            confidence="high",
            page_url="https://python.org",
            timestamp="2024-01-01T00:00:00+00:00",
        ),
        EvidenceItem(
            evidence_id="ev-002",
            evidence_type="META_DESCRIPTION",
            extractor_source="seo",
            value="The official home of the Python Programming Language",
            provenance=EvidenceProvenance(page_url="https://python.org"),
            confidence="high",
            page_url="https://python.org",
            timestamp="2024-01-01T00:00:00+00:00",
        ),
        EvidenceItem(
            evidence_id="ev-003",
            evidence_type="CANONICAL",
            extractor_source="seo",
            value="https://python.org",
            provenance=EvidenceProvenance(page_url="https://python.org"),
            confidence="high",
            page_url="https://python.org",
            timestamp="2024-01-01T00:00:00+00:00",
        ),
        EvidenceItem(
            evidence_id="ev-004",
            evidence_type="LANGUAGE",
            extractor_source="seo",
            value={"value": "en"},
            provenance=EvidenceProvenance(page_url="https://python.org"),
            confidence="high",
            page_url="https://python.org",
            timestamp="2024-01-01T00:00:00+00:00",
        ),
        EvidenceItem(
            evidence_id="ev-005",
            evidence_type="CHARSET",
            extractor_source="seo",
            value="UTF-8",
            provenance=EvidenceProvenance(page_url="https://python.org"),
            confidence="high",
            page_url="https://python.org",
            timestamp="2024-01-01T00:00:00+00:00",
        ),
        EvidenceItem(
            evidence_id="ev-006",
            evidence_type="VIEWPORT",
            extractor_source="seo",
            value="width=device-width, initial-scale=1",
            provenance=EvidenceProvenance(page_url="https://python.org"),
            confidence="high",
            page_url="https://python.org",
            timestamp="2024-01-01T00:00:00+00:00",
        ),
        EvidenceItem(
            evidence_id="ev-007",
            evidence_type="STRUCTURED_DATA",
            extractor_source="seo",
            value={"has_json_ld": True, "has_microdata": False, "has_rdfa": False},
            provenance=EvidenceProvenance(page_url="https://python.org"),
            confidence="high",
            page_url="https://python.org",
            timestamp="2024-01-01T00:00:00+00:00",
        ),
        EvidenceItem(
            evidence_id="ev-008",
            evidence_type="SITE_NAME",
            extractor_source="metadata",
            value="Python.org",
            provenance=EvidenceProvenance(page_url="https://python.org"),
            confidence="high",
            page_url="https://python.org",
            timestamp="2024-01-01T00:00:00+00:00",
        ),
        EvidenceItem(
            evidence_id="ev-009",
            evidence_type="FAVICON",
            extractor_source="metadata",
            value="https://python.org/static/favicon.ico",
            provenance=EvidenceProvenance(page_url="https://python.org"),
            confidence="high",
            page_url="https://python.org",
            timestamp="2024-01-01T00:00:00+00:00",
        ),
        EvidenceItem(
            evidence_id="ev-010",
            evidence_type="RSS_FEED",
            extractor_source="metadata",
            value="https://python.org/feeds/news.xml",
            provenance=EvidenceProvenance(page_url="https://python.org"),
            confidence="high",
            page_url="https://python.org",
            timestamp="2024-01-01T00:00:00+00:00",
        ),
        EvidenceItem(
            evidence_id="ev-011",
            evidence_type="TECHNOLOGY",
            extractor_source="technology",
            value={
                "name": "Python",
                "category": "language",
                "confidence": "high",
                "detection_method": "fingerprint",
            },
            provenance=EvidenceProvenance(page_url="https://python.org"),
            confidence="high",
            page_url="https://python.org",
            timestamp="2024-01-01T00:00:00+00:00",
        ),
        EvidenceItem(
            evidence_id="ev-012",
            evidence_type="TECHNOLOGY",
            extractor_source="technology",
            value={
                "name": "Nginx",
                "category": "web-server",
                "confidence": "high",
                "detection_method": "fingerprint",
            },
            provenance=EvidenceProvenance(page_url="https://python.org"),
            confidence="high",
            page_url="https://python.org",
            timestamp="2024-01-01T00:00:00+00:00",
        ),
        EvidenceItem(
            evidence_id="ev-013",
            evidence_type="CONTENT_HEADING",
            extractor_source="content",
            value={"level": 1, "text": "Welcome to Python.org"},
            provenance=EvidenceProvenance(page_url="https://python.org"),
            confidence="high",
            page_url="https://python.org",
            timestamp="2024-01-01T00:00:00+00:00",
        ),
        EvidenceItem(
            evidence_id="ev-014",
            evidence_type="CONTENT_HEADING",
            extractor_source="content",
            value={"level": 2, "text": "Downloads"},
            provenance=EvidenceProvenance(page_url="https://python.org"),
            confidence="high",
            page_url="https://python.org",
            timestamp="2024-01-01T00:00:00+00:00",
        ),
        EvidenceItem(
            evidence_id="ev-015",
            evidence_type="CONTENT_HEADING",
            extractor_source="content",
            value={"level": 2, "text": "Documentation"},
            provenance=EvidenceProvenance(page_url="https://python.org"),
            confidence="high",
            page_url="https://python.org",
            timestamp="2024-01-01T00:00:00+00:00",
        ),
        EvidenceItem(
            evidence_id="ev-016",
            evidence_type="CONTENT_HEADING",
            extractor_source="content",
            value={"level": 2, "text": "Community"},
            provenance=EvidenceProvenance(page_url="https://python.org"),
            confidence="high",
            page_url="https://python.org",
            timestamp="2024-01-01T00:00:00+00:00",
        ),
        EvidenceItem(
            evidence_id="ev-017",
            evidence_type="SOCIAL_PROFILE",
            extractor_source="social",
            value={
                "platform": "GitHub",
                "url": "https://github.com/python",
                "username": "python",
            },
            provenance=EvidenceProvenance(page_url="https://python.org"),
            confidence="high",
            page_url="https://python.org",
            timestamp="2024-01-01T00:00:00+00:00",
        ),
        EvidenceItem(
            evidence_id="ev-018",
            evidence_type="COMPETITOR",
            extractor_source="competitors",
            value={"name": "Ruby", "url": "https://ruby-lang.org"},
            provenance=EvidenceProvenance(page_url="https://python.org"),
            confidence="medium",
            page_url="https://python.org",
            timestamp="2024-01-01T00:00:00+00:00",
        ),
    ],
    diagnostics={
        "total_evidence_items": 18,
        "seo_items": 7,
        "metadata_items": 3,
        "technology_items": 2,
        "content_items": 4,
        "social_items": 1,
        "competitor_items": 1,
        "build_timestamp": "2024-01-01T00:00:00+00:00",
    },
)

summary = summarize(schema)
html = (
    "<html><head><style>"
    "body{font-family:system-ui,sans-serif;max-width:900px;margin:40px auto;"
    "padding:0 20px;line-height:1.6;color:#222}"
    "table{border-collapse:collapse;width:100%;margin:16px 0}"
    "th,td{border:1px solid #ddd;padding:8px;text-align:left}"
    "th{background:#f5f5f5}"
    "code{background:#f4f4f4;padding:2px 6px;border-radius:4px}"
    "</style></head><body><pre>"
    + summary.text.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
    + "</pre></body></html>"
)
with open("assets/screenshots/markdown-report.html", "w", encoding="utf-8") as f:
    f.write(html)
print("HTML report written.")
